In [1]:
from IPython.core.display import display, HTML
display(HTML("<style>.container { width:90% !important; }</style>"))

In [2]:
import pandas as pd
from fredapi import Fred

In [3]:
#paper 7

df_fred_md = pd.read_csv("https://files.stlouisfed.org/files/htdocs/fred-md/monthly/current.csv")
df_fred_md = df_fred_md.iloc[1:,:]

df_paper7_features = df_fred_md[["sasdate","AAA","AAAFFM","AMDMNOx","AMDMUOx","AWHMAN","AWOTMAN","BAA","BAAFFM","BUSINVx","BUSLOANS","CE16OV",
              "CES0600000007","CES0600000008","CES1021000001","CES2000000008","CES3000000008","CLAIMSx","CLF16OV","CMRMTSPLx","COMPAPFFx","CONSPI","CP3Mx","CPIAPPSL",
              "CPIAUCSL","CPIMEDSL","CPITRNSL","CPIULFSL","CUMFNS","CUSR0000SA0L2","CUSR0000SA0L5","CUSR0000SAC","CUSR0000SAD","CUSR0000SAS","DDURRG3M086SBEA","DMANEMP",
              "DNDGRG3M086SBEA","DPCERA3M086SBEA","DSERRG3M086SBEA","DTCOLNVHFNM","DTCTHFNM","EXCAUSx","EXJPUSx","EXSZUSx","EXUSUKx","FEDFUNDS","GS1","GS10","GS5","HOUST",
              "HOUSTMW","HOUSTNE","HOUSTS","HOUSTW","HWI","HWIURATIO","INDPRO","INVEST","IPB51222S","IPBUSEQ","IPCONGD","IPDCONGD","IPDMAT","IPFINAL","IPFPNSS","IPFUELS",
              "IPMANSICS","IPMAT","IPNCONGD","IPNMAT","ISRATIOx","M1SL","M2REAL","M2SL","MANEMP","NDMANEMP","NONBORRES","NONREVSL","OILPRICEx","PAYEMS","PCEPI","PERMIT",
              "PERMITMW","PERMITNE","PERMITS","PERMITW","PPICMM","REALLN","RETAILx","RPI","S&P 500","S&P div yield","S&P PE ratio","S&P: indust","SRVPRD","T10YFFM","T1YFFM",
              "T5YFFM","TB3MS","TB3SMFFM","TB6MS","TB6SMFFM","TOTRESNS","UEMP15OV","UEMP15T26","UEMP27OV","UEMP5TO14","UEMPLT5","UEMPMEAN","UNRATE","USCONS","USFIRE",
              "USGOOD","USGOVT","USTPU","USTRADE","USWTRADE","W875RX1","WPSFD49207","WPSFD49502","WPSID61","WPSID62"]]

df_paper7_features

,sasdate,AAA,AAAFFM,AMDMNOx,AMDMUOx,AWHMAN,AWOTMAN,BAA,BAAFFM,BUSINVx,...,USGOOD,USGOVT,USTPU,USTRADE,USWTRADE,W875RX1,WPSFD49207,WPSFD49502,WPSID61,WPSID62
1,1/1/1959,4.12,1.64,14716.48296,4.262035e+04,40.2,2.5,4.87,2.39,8.488956e+04,...,18796.0,8105.0,10774.0,5350.3,2568.7,2293.2,33.100,33.400,30.600,31.600
2,2/1/1959,4.14,1.71,15400.24873,4.367715e+04,40.3,2.6,4.89,2.46,8.518181e+04,...,18890.0,8116.0,10816.0,5381.3,2575.4,2301.5,33.200,33.400,30.700,31.400
3,3/1/1959,4.13,1.33,15745.42348,4.478165e+04,40.4,2.8,4.85,2.05,8.562019e+04,...,19069.0,8132.0,10873.0,5431.6,2584.4,2318.5,33.200,33.300,30.700,31.500
4,4/1/1959,4.23,1.27,15919.42165,4.552275e+04,40.5,2.9,4.86,1.90,8.676972e+04,...,19269.0,8142.0,10905.0,5395.4,2596.9,2334.9,33.200,33.400,30.700,31.700
5,5/1/1959,4.37,1.47,15248.82330,4.538445e+04,40.7,2.9,4.96,2.06,8.726654e+04,...,19378.0,8153.0,10949.0,5456.3,2607.4,2350.4,33.300,33.300,30.900,31.500
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
756,12/1/2021,2.65,2.56,273281.00000,1.271825e+06,41.4,4.1,3.30,3.22,2.208693e+06,...,20691.0,22141.0,28163.0,15595.1,5749.7,14398.0,232.025,248.997,248.651,265.564
757,1/1/2022,2.93,2.85,277490.00000,1.283035e+06,41.2,4.2,3.58,3.50,2.237408e+06,...,20723.0,22153.0,28351.0,15716.5,5762.3,14378.0,235.688,253.440,253.955,272.778
758,2/1/2022,3.25,3.17,272718.00000,1.289294e+06,41.6,4.4,3.97,3.89,2.270332e+06,...,20825.0,22164.0,28550.0,15826.8,5781.9,14432.6,241.766,261.364,257.816,308.304
759,3/1/2022,3.43,3.23,275013.00000,1.294611e+06,41.7,4.2,4.29,4.09,NaN,...,20885.0,22169.0,28604.0,15875.8,5788.9,14388.7,246.336,267.243,263.120,304.087
760,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [4]:
start_date = '1959-01-01'
end_date = '2022-03-01'

# Fred API key: ab766afb0df13dba8492403a7865f852
fred = Fred(api_key = 'ab766afb0df13dba8492403a7865f852')

df7 = {}
df7['AMBSL'] = fred.get_series('AMBSL', observation_start=start_date, observation_end=end_date)
df7['MZMSL'] = fred.get_series('MZMSL', observation_start=start_date, observation_end=end_date)
df7 = pd.DataFrame(df7)
df7

             AMBSL    MZMSL
1959-01-01  38.756    274.9
1959-02-01  38.895    276.0
1959-03-01  38.896    277.4
1959-04-01  39.009    278.1
1959-05-01  39.089    280.1
...            ...      ...
2020-09-01     NaN  21204.8
2020-10-01     NaN  21337.3
2020-11-01     NaN  21553.8
2020-12-01     NaN  21715.7
2021-01-01     NaN  21965.8

[745 rows x 2 columns]

In [ ]:
# 1 feature not implemented yet for Paper 7

# VXOCLSx